### ISSUE TITLE
API fix request

### ISSUE THREAD

**Issue by JacobAMason** [jjs451/SWArch-Scandals#12]
The Activity endpoint is capitalized in swagger, but is lowercase in implementation. Please lowercase this in swagger and reversion to 1.0.1

**Comment by jjs451** [comment]
Should be done, new swagger url is https://app.swaggerhub.com/apis/MSU-CSE4233-Team7/Scandals/1.0.1

**Comment by JacobAMason** [comment]
Please mark the API as published
