### ISSUE TITLE
500 on /activity endpoint

### ISSUE THREAD

**Issue by JacobAMason** [jjs451/SWArch-Scandals#20]
`GET http://35.196.71.129/activity/?location=Atlanta,%20GA&endDate=2017-12-03T00:00:00&startDate=2017-12-01T00:00:00` throws a 500

**Comment by jjs451** [comment]
Is it still happening?  Right now its returning an empty 200 for me and I don't see a 500 in the log

**Comment by JacobAMason** [comment]
No, it appears to be working again. I think it was fixed in b3fc970a5c99ddd7208cf3879cea998315bdfaee
